### ISSUE TITLE
Device or resource busy (Beaglebone Black)

### ISSUE THREAD

**Issue by alxx** [zeiv/SSD1306-ruby#11]
Hi,

I'm using a brand new BBB running Debian, and I'm trying to initialise the display thus:

> disp = SSD1306::Display.new protocol: :i2c, path: '/dev/i2c-1', address: 0x7B
Errno::EBUSY: Device or resource busy @ rb_io_syswrite - /dev/i2c-1

The address I've got from the back of the OLED, it's one of two options (the other being 0x7A) and this one is jumper-set.

I don't know how to check the device tree, but this is the first I2C connection I'm making on this new board, so I wouldn't think it's already used by something else?

**Comment by alxx** [comment]
The address had to be converted; `i2cdetect -r 2` revealed it to be 0x3c.
It's working, yay!

**Comment by viacommits** [comment]
> The address had to be converted; `i2cdetect -r 2` revealed it to be 0x3c.
> It's working, yay!

Hey, sorry for the late reply.  Glad you got it working!
